(function($){
  $.fn.extend({
    licencePlateForm : function() {
      this.each( function() {
        if ($(this).is("form")) {
          $(this).submit($.LicensePlate.onSubmit);
        }
        else {
          throw new Error("Works only with form elements");
        }
      });
      return this;
    }
  });

  $.LicensePlate = {
    parseData : function(input) {
      input = $(input);
      var preview = input.parents(".line").find(".preview");
      var data = input.val().split("-");

      if (data.length != 2) { return false; }
      
      var county = data[0];

      data = data[1].split(" ");
      if (data.length != 2) { return false; }

      var letters = data[0];
      var numbers = data[1];

      return {county : county, letters : letters, numbers : numbers }
    },
    transformCharacter : function(character) {
      if (character.match(/[0-9]/)) {
        return $.LicensePlate.transformNumber(character);
      }
      else if (character.match(/[a-zäöü]/)) {
        return $.LicensePlate.transformLetter(character.toUpperCase());
      }
      else if (character.match(/[A-ZÄÖÜ]/)) {
        return $.LicensePlate.transformLetter(character);
      }
      else if (character.match(/ /)) {
        return $.LicensePlate.generateWhitespace();
      }
      else {
        return false;
      }
    },
    transformLetter : function( letter ) {
      switch(letter) {
        case "Ä":
          return $("<span class='character letter AE'>" + letter + "</span>");
        case "Ö":
          return $("<span class='character letter OE'>" + letter + "</span>");
        case "Ü":
          return $("<span class='character letter UE'>" + letter + "</span>");
        default:
          return $("<span class='character letter " + letter + "'>" + letter + "</span>");
      }
    },
    transformNumber : function( num ) {
      return $("<span class='character number no" + num + "''>" + num + "</span>");
    },
    generateSeparator : function() {
      return $("<span class='separator'>-</span>");
    },
    generateWhitespace : function() {
      return $("<span class='whitespace'>&nbsp;</span>");
    },
    generateLink : function(code) {
      return $("<a href='?" + code + "'>" + code + "</a>");
    },
    codeStateMapping : {
      "A"   : "Bayern",
      "AA"  : "Baden-Württemberg",
      "AB"  : "Bayern",
      "ABG" : "Thüringen",
      "ABI" : "Sachsen-Anhalt",
      "AC"  : "Nordrhein-Westfalen",
      "AE"  : "Sachsen",
      "AH"  : "Nordrhein-Westfalen",
      "AIB" : "Bayern",
      "AIC" : "Bayern",
      "AK"  : "Rheinland-Pfalz",
      "ALF" : "Niedersachsen",
      "ALZ" : "Bayern",
      "AM"  : "Bayern",
      "AN"  : "Bayern",
      "ANA" : "Sachsen",
      "ANG" : "Brandenburg",
      "ANK" : "Mecklenburg-Vorpommern",
      "AÖ"  : "Bayern",
      "AP"  : "Thüringen",
      "APD" : "Thüringen",
      "ARN" : "Thüringen",
      "ART" : "Thüringen",
      "AS"  : "Bayern",
      "ASL" : "Sachsen-Anhalt",
      "ASZ" : "Sachsen",
      "AT"  : "Mecklenburg-Vorpommern",
      "AU"  : "Sachsen",
      "AUR" : "Niedersachsen",
      "AW"  : "Rheinland-Pfalz",
      "AZ"  : "Rheinland-Pfalz",
      "AZE" : "Sachsen-Anhalt",
      "B"   : "Berlin",
      "BA"  : "Bayern",
      "BAD" : "Baden-Württemberg",
      "BAR" : "Brandenburg",
      "BB"  : "Baden-Württemberg",
      "BBG" : "Sachsen-Anhalt",
      "BBL" : "Brandenburg",
      "BC"  : "Baden-Württemberg",
      "BCH" : "Baden-Württemberg",
      "BE"  : "Nordrhein-Westfalen",
      "BED" : "Sachsen",
      "BER" : "Brandenburg",
      "BF"  : "Nordrhein-Westfalen",
      "BGD" : "Bayern",
      "BGL" : "Bayern",
      "BH"  : "Baden-Württemberg",
      "BI"  : "Nordrhein-Westfalen",
      "BID" : "Hessen",
      "BIN" : "Rheinland-Pfalz",
      "BIR" : "Rheinland-Pfalz",
      "BIT" : "Rheinland-Pfalz",
      "BIW" : "Sachsen",
      "BK"  : "Baden-Württemberg",
      "BKS" : "Rheinland-Pfalz",
      "BL"  : "Baden-Württemberg",
      "BLB" : "Nordrhein-Westfalen",
      "BLK" : "Sachsen-Anhalt",
      "BM"  : "Nordrhein-Westfalen",
      "BN"  : "Nordrhein-Westfalen",
      "BNA" : "Sachsen",
      "BO"  : "Nordrhein-Westfalen",
      "BÖ"  : "Sachsen-Anhalt",
      "BOG" : "Bayern",
      "BOH" : "Nordrhein-Westfalen",
      "BOR" : "Nordrhein-Westfalen",
      "BOT" : "Nordrhein-Westfalen",
      "BRA" : "Niedersachsen",
      "BRB" : "Brandenburg",
      "BRG" : "Sachsen-Anhalt",
      "BRK" : "Bayern",
      "BRL" : "Niedersachsen",
      "BRV" : "Niedersachsen",
      "BS"  : "Niedersachsen",
      "BSB" : "Niedersachsen",
      "BSK" : "Brandenburg",
      "BT"  : "Bayern",
      "BTF" : "Sachsen-Anhalt",
      "BÜD" : "Hessen",
      "BUL" : "Bayern",
      "BÜR" : "Nordrhein-Westfalen",
      "BÜS" : "Baden-Württemberg",
      "BÜZ" : "Mecklenburg-Vorpommern",
      "BWL" : "Baden-Württemberg",
      "BYL" : "Bayern",
      "BZ"  : "Sachsen",
      "C"   : "Sachsen",
      "CA"  : "Brandenburg",
      "CAS" : "Nordrhein-Westfalen",
      "CB"  : "Brandenburg",
      "CE"  : "Niedersachsen",
      "CHA" : "Bayern",
      "CLP" : "Niedersachsen",
      "CLZ" : "Niedersachsen",
      "CO"  : "Bayern",
      "COC" : "Rheinland-Pfalz",
      "COE" : "Nordrhein-Westfalen",
      "CR"  : "Baden-Württemberg",
      "CUX" : "Niedersachsen",
      "CW"  : "Baden-Württemberg",
      "D"   : "Nordrhein-Westfalen",
      "DA"  : "Hessen",
      "DAH" : "Bayern",
      "DAN" : "Niedersachsen",
      "DAU" : "Rheinland-Pfalz",
      "DBR" : "Mecklenburg-Vorpommern",
      "DD"  : "Sachsen",
      "DE"  : "Sachsen-Anhalt",
      "DEG" : "Bayern",
      "DEL" : "Niedersachsen",
      "DGF" : "Bayern",
      "DH"  : "Niedersachsen",
      "DI"  : "Hessen",
      "DIL" : "Hessen",
      "DIN" : "Nordrhein-Westfalen",
      "DIZ" : "Rheinland-Pfalz",
      "DKB" : "Bayern",
      "DL"  : "Sachsen",
      "DLG" : "Bayern",
      "DM"  : "Mecklenburg-Vorpommern",
      "DN"  : "Nordrhein-Westfalen",
      "DO"  : "Nordrhein-Westfalen",
      "DON" : "Bayern",
      "DU"  : "Nordrhein-Westfalen",
      "DUD" : "Niedersachsen",
      "DÜW" : "Rheinland-Pfalz",
      "DW"  : "Sachsen",
      "DZ"  : "Sachsen",
      "E"   : "Nordrhein-Westfalen",
      "EA"  : "Thüringen",
      "EB"  : "Sachsen",
      "EBE" : "Bayern",
      "EBN" : "Bayern",
      "EBS" : "Bayern",
      "ECK" : "Schleswig-Holstein",
      "ED"  : "Bayern",
      "EE"  : "Brandenburg",
      "EF"  : "Thüringen",
      "EG"  : "Bayern",
      "EH"  : "Brandenburg",
      "EI"  : "Bayern",
      "EIC" : "Thüringen",
      "EIL" : "Sachsen-Anhalt",
      "EIN" : "Niedersachsen",
      "EIS" : "Thüringen",
      "EL"  : "Niedersachsen",
      "EM"  : "Baden-Württemberg",
      "EMD" : "Niedersachsen",
      "EMS" : "Rheinland-Pfalz",
      "EN"  : "Nordrhein-Westfalen",
      "ER"  : "Bayern",
      "ERB" : "Hessen",
      "ERH" : "Bayern",
      "ERK" : "Nordrhein-Westfalen",
      "ERZ" : "Sachsen",
      "ES"  : "Baden-Württemberg",
      "ESB" : "Bayern",
      "ESW" : "Hessen",
      "EU"  : "Nordrhein-Westfalen",
      "EW"  : "Brandenburg",
      "F"   : "Hessen",
      "FB"  : "Hessen",
      "FD"  : "Hessen",
      "FDB" : "Bayern",
      "FDS" : "Baden-Württemberg",
      "FEU" : "Bayern",
      "FF"  : "Brandenburg",
      "FFB" : "Bayern",
      "FG"  : "Sachsen",
      "FI"  : "Brandenburg",
      "FKB" : "Hessen",
      "FL"  : "Schleswig-Holstein",
      "FLÖ" : "Sachsen",
      "FN"  : "Baden-Württemberg",
      "FO"  : "Bayern",
      "FOR" : "Brandenburg",
      "FR"  : "Baden-Württemberg",
      "FRG" : "Bayern",
      "FRI" : "Niedersachsen",
      "FRW" : "Brandenburg",
      "FS"  : "Bayern",
      "FT"  : "Rheinland-Pfalz",
      "FTL" : "Sachsen",
      "FÜ"  : "Bayern",
      "FÜS" : "Bayern",
      "FW"  : "Brandenburg",
      "FZ"  : "Hessen",
      "G"   : "Thüringen",
      "GA"  : "Sachsen-Anhalt",
      "GAN" : "Niedersachsen",
      "GAP" : "Bayern",
      "GC"  : "Sachsen",
      "GD"  : "Baden-Württemberg",
      "GDB" : "Mecklenburg-Vorpommern",
      "GE"  : "Nordrhein-Westfalen",
      "GEL" : "Nordrhein-Westfalen",
      "GEO" : "Bayern",
      "GER" : "Rheinland-Pfalz",
      "GF"  : "Niedersachsen",
      "GG"  : "Hessen",
      "GHA" : "Sachsen",
      "GHC" : "Sachsen-Anhalt",
      "GI"  : "Hessen",
      "GK"  : "Nordrhein-Westfalen",
      "GL"  : "Nordrhein-Westfalen",
      "GLA" : "Nordrhein-Westfalen",
      "GM"  : "Nordrhein-Westfalen",
      "GMN" : "Mecklenburg-Vorpommern",
      "GN"  : "Hessen",
      "GNT" : "Sachsen-Anhalt",
      "GÖ"  : "Niedersachsen",
      "GOA" : "Rheinland-Pfalz",
      "GOH" : "Rheinland-Pfalz",
      "GP"  : "Baden-Württemberg",
      "GR"  : "Sachsen",
      "GRA" : "Bayern",
      "GRH" : "Sachsen",
      "GRI" : "Bayern",
      "GRM" : "Sachsen",
      "GRZ" : "Thüringen",
      "GS"  : "Niedersachsen",
      "GT"  : "Nordrhein-Westfalen",
      "GTH" : "Thüringen",
      "GÜ"  : "Mecklenburg-Vorpommern",
      "GUB" : "Brandenburg",
      "GUN" : "Bayern",
      "GV"  : "Nordrhein-Westfalen",
      "GVM" : "Mecklenburg-Vorpommern",
      "GW"  : "Mecklenburg-Vorpommern",
      "GZ"  : "Bayern",
      "H"   : "Niedersachsen",
      "HA"  : "Nordrhein-Westfalen",
      "HAB" : "Bayern",
      "HAL" : "Sachsen-Anhalt",
      "HAM" : "Nordrhein-Westfalen",
      "HAS" : "Bayern",
      "HB"  : "Bremen",
      "HBN" : "Thüringen",
      "HBS" : "Sachsen-Anhalt",
      "HC"  : "Sachsen",
      "HCH" : "Baden-Württemberg",
      "HD"  : "Baden-Württemberg",
      "HDH" : "Baden-Württemberg",
      "HDL" : "Sachsen-Anhalt",
      "HE"  : "Niedersachsen",
      "HEB" : "Bayern",
      "HEF" : "Hessen",
      "HEI" : "Schleswig-Holstein",
      "HEL" : "Hessen",
      "HER" : "Nordrhein-Westfalen",
      "HET" : "Sachsen-Anhalt",
      "HF"  : "Nordrhein-Westfalen",
      "HG"  : "Hessen",
      "HGN" : "Mecklenburg-Vorpommern",
      "HGW" : "Mecklenburg-Vorpommern",
      "HH"  : "Hamburg",
      "HHM" : "Sachsen-Anhalt",
      "HI"  : "Niedersachsen",
      "HIG" : "Thüringen",
      "HIP" : "Bayern",
      "HK"  : "Niedersachsen",
      "HL"  : "Schleswig-Holstein",
      "HM"  : "Niedersachsen",
      "HMÜ" : "Niedersachsen",
      "HN"  : "Baden-Württemberg",
      "HO"  : "Bayern",
      "HOG" : "Hessen",
      "HOH" : "Bayern",
      "HOL" : "Niedersachsen",
      "HOM" : "Saarland",
      "HOR" : "Baden-Württemberg",
      "HÖS" : "Bayern",
      "HOT" : "Sachsen",
      "HP"  : "Hessen",
      "HR"  : "Hessen",
      "HRO" : "Mecklenburg-Vorpommern",
      "HS"  : "Nordrhein-Westfalen",
      "HSK" : "Nordrhein-Westfalen",
      "HST" : "Mecklenburg-Vorpommern",
      "HU"  : "Hessen",
      "HV"  : "Sachsen-Anhalt",
      "HVL" : "Brandenburg",
      "HWI" : "Mecklenburg-Vorpommern",
      "HX"  : "Nordrhein-Westfalen",
      "HY"  : "Sachsen",
      "HZ"  : "Sachsen-Anhalt",
      "IGB" : "Saarland",
      "IK"  : "Thüringen",
      "IL"  : "Thüringen",
      "ILL" : "Bayern",
      "IN"  : "Bayern",
      "IZ"  : "Schleswig-Holstein",
      "J"   : "Thüringen",
      "JE"  : "Sachsen-Anhalt",
      "JL"  : "Sachsen-Anhalt",
      "JÜL" : "Nordrhein-Westfalen",
      "K"   : "Nordrhein-Westfalen",
      "KA"  : "Baden-Württemberg",
      "KB"  : "Hessen",
      "KC"  : "Bayern",
      "KE"  : "Bayern",
      "KEH" : "Bayern",
      "KEL" : "Baden-Württemberg",
      "KEM" : "Bayern",
      "KF"  : "Bayern",
      "KG"  : "Bayern",
      "KH"  : "Rheinland-Pfalz",
      "KI"  : "Schleswig-Holstein",
      "KIB" : "Rheinland-Pfalz",
      "KK"  : "Nordrhein-Westfalen",
      "KL"  : "Rheinland-Pfalz",
      "KLE" : "Nordrhein-Westfalen",
      "KLZ" : "Sachsen-Anhalt",
      "KM"  : "Sachsen",
      "KN"  : "Baden-Württemberg",
      "KO"  : "Rheinland-Pfalz",
      "KÖN" : "Bayern",
      "KÖT" : "Sachsen-Anhalt",
      "KÖZ" : "Bayern",
      "KR"  : "Nordrhein-Westfalen",
      "KRU" : "Bayern",
      "KS"  : "Hessen",
      "KT"  : "Bayern",
      "KU"  : "Bayern",
      "KÜN" : "Baden-Württemberg",
      "KUS" : "Rheinland-Pfalz",
      "KW"  : "Brandenburg",
      "KY"  : "Brandenburg",
      "KYF" : "Thüringen",
      "L"   : "Sachsen",
      "LA"  : "Bayern",
      "LAN" : "Bayern",
      "LAU" : "Bayern",
      "LB"  : "Baden-Württemberg",
      "LBS" : "Thüringen",
      "LBZ" : "Mecklenburg-Vorpommern",
      "LC"  : "Brandenburg",
      "LD"  : "Rheinland-Pfalz",
      "LDK" : "Hessen",
      "LDS" : "Brandenburg",
      "LEO" : "Baden-Württemberg",
      "LER" : "Niedersachsen",
      "LEV" : "Nordrhein-Westfalen",
      "LF"  : "Bayern",
      "LG"  : "Niedersachsen",
      "LH"  : "Nordrhein-Westfalen",
      "LI"  : "Bayern",
      "LIB" : "Brandenburg",
      "LIF" : "Bayern",
      "LIP" : "Nordrhein-Westfalen",
      "LL"  : "Bayern",
      "LM"  : "Hessen",
      "LN"  : "Brandenburg",
      "LÖ"  : "Baden-Württemberg",
      "LÖB" : "Sachsen",
      "LOS" : "Brandenburg",
      "LP"  : "Nordrhein-Westfalen",
      "LR"  : "Baden-Württemberg",
      "LRO" : "Mecklenburg-Vorpommern",
      "LSA" : "Sachsen-Anhalt",
      "LSN" : "Sachsen",
      "LSZ" : "Thüringen",
      "LU"  : "Rheinland-Pfalz",
      "LÜN" : "Nordrhein-Westfalen",
      "LUP" : "Mecklenburg-Vorpommern",
      "LWL" : "Mecklenburg-Vorpommern",
      "M"   : "Bayern",
      "MA"  : "Baden-Württemberg",
      "MAB" : "Sachsen",
      "MAI" : "Bayern",
      "MAK" : "Bayern",
      "MAL" : "Bayern",
      "MB"  : "Bayern",
      "MC"  : "Mecklenburg-Vorpommern",
      "MD"  : "Sachsen-Anhalt",
      "ME"  : "Nordrhein-Westfalen",
      "MED" : "Schleswig-Holstein",
      "MEG" : "Hessen",
      "MEI" : "Sachsen",
      "MEK" : "Sachsen",
      "MEL" : "Niedersachsen",
      "MER" : "Sachsen-Anhalt",
      "MET" : "Bayern",
      "MG"  : "Nordrhein-Westfalen",
      "MGH" : "Baden-Württemberg",
      "MGN" : "Thüringen",
      "MH"  : "Nordrhein-Westfalen",
      "MHL" : "Thüringen",
      "MI"  : "Nordrhein-Westfalen",
      "MIL" : "Bayern",
      "MK"  : "Nordrhein-Westfalen",
      "MKK" : "Hessen",
      "ML"  : "Sachsen-Anhalt",
      "MM"  : "Bayern",
      "MN"  : "Bayern",
      "MO"  : "Nordrhein-Westfalen",
      "MOD" : "Bayern",
      "MOL" : "Brandenburg",
      "MON" : "Nordrhein-Westfalen",
      "MOS" : "Baden-Württemberg",
      "MQ"  : "Sachsen-Anhalt",
      "MR"  : "Hessen",
      "MS"  : "Nordrhein-Westfalen",
      "MSE" : "Mecklenburg-Vorpommern",
      "MSH" : "Sachsen-Anhalt",
      "MSP" : "Bayern",
      "MST" : "Mecklenburg-Vorpommern",
      "MTK" : "Hessen",
      "MTL" : "Sachsen",
      "MÜ"  : "Bayern",
      "MÜB" : "Bayern",
      "MÜR" : "Mecklenburg-Vorpommern",
      "MVL" : "Mecklenburg-Vorpommern",
      "MW"  : "Sachsen",
      "MY"  : "Rheinland-Pfalz",
      "MYK" : "Rheinland-Pfalz",
      "MZ"  : "Rheinland-Pfalz",
      "MZG" : "Saarland",
      "N"   : "Bayern",
      "NAB" : "Bayern",
      "NAI" : "Bayern",
      "NAU" : "Brandenburg",
      "NB"  : "Mecklenburg-Vorpommern",
      "ND"  : "Bayern",
      "NDH" : "Thüringen",
      "NE"  : "Nordrhein-Westfalen",
      "NEA" : "Bayern",
      "NEB" : "Sachsen-Anhalt",
      "NEC" : "Bayern",
      "NEN" : "Bayern",
      "NES" : "Bayern",
      "NEW" : "Bayern",
      "NF"  : "Schleswig-Holstein",
      "NH"  : "Thüringen",
      "NI"  : "Niedersachsen",
      "NK"  : "Saarland",
      "NL"  : "Niedersachsen",
      "NM"  : "Bayern",
      "NMB" : "Sachsen-Anhalt",
      "NMS" : "Schleswig-Holstein",
      "NÖ"  : "Bayern",
      "NOH" : "Niedersachsen",
      "NOL" : "Sachsen",
      "NOM" : "Niedersachsen",
      "NOR" : "Niedersachsen",
      "NP"  : "Brandenburg",
      "NR"  : "Rheinland-Pfalz",
      "NRW" : "Nordrhein-Westfalen",
      "NT"  : "Baden-Württemberg",
      "NU"  : "Bayern",
      "NVP" : "Mecklenburg-Vorpommern",
      "NW"  : "Rheinland-Pfalz",
      "NWM" : "Mecklenburg-Vorpommern",
      "NY"  : "Sachsen",
      "NZ"  : "Mecklenburg-Vorpommern",
      "OA"  : "Bayern",
      "OAL" : "Bayern",
      "OB"  : "Nordrhein-Westfalen",
      "OBB" : "Bayern",
      "OBG" : "Sachsen-Anhalt",
      "OC"  : "Sachsen-Anhalt",
      "OCH" : "Bayern",
      "OD"  : "Schleswig-Holstein",
      "OE"  : "Nordrhein-Westfalen",
      "OF"  : "Hessen",
      "OG"  : "Baden-Württemberg",
      "OH"  : "Schleswig-Holstein",
      "OHA" : "Niedersachsen",
      "ÖHR" : "Baden-Württemberg",
      "OHV" : "Brandenburg",
      "OHZ" : "Niedersachsen",
      "OK"  : "Sachsen-Anhalt",
      "OL"  : "Niedersachsen",
      "OP"  : "Nordrhein-Westfalen",
      "OPR" : "Brandenburg",
      "OS"  : "Niedersachsen",
      "OSL" : "Brandenburg",
      "OTW" : "Saarland",
      "OVI" : "Bayern",
      "OVL" : "Sachsen",
      "OVP" : "Mecklenburg-Vorpommern",
      "OZ"  : "Sachsen",
      "P"   : "Brandenburg",
      "PA"  : "Bayern",
      "PAF" : "Bayern",
      "PAN" : "Bayern",
      "PAR" : "Bayern",
      "PB"  : "Nordrhein-Westfalen",
      "PCH" : "Mecklenburg-Vorpommern",
      "PE"  : "Niedersachsen",
      "PEG" : "Bayern",
      "PF"  : "Baden-Württemberg",
      "PI"  : "Schleswig-Holstein",
      "PIR" : "Sachsen",
      "PL"  : "Sachsen",
      "PLÖ" : "Schleswig-Holstein",
      "PM"  : "Brandenburg",
      "PN"  : "Thüringen",
      "PR"  : "Brandenburg",
      "PRÜ" : "Rheinland-Pfalz",
      "PS"  : "Rheinland-Pfalz",
      "PW"  : "Mecklenburg-Vorpommern",
      "PZ"  : "Brandenburg",
      "QFT" : "Sachsen-Anhalt",
      "QLB" : "Sachsen-Anhalt",
      "R"   : "Bayern",
      "RA"  : "Baden-Württemberg",
      "RC"  : "Sachsen",
      "RD"  : "Schleswig-Holstein",
      "RDG" : "Mecklenburg-Vorpommern",
      "RE"  : "Nordrhein-Westfalen",
      "REG" : "Bayern",
      "REH" : "Bayern",
      "REI" : "Bayern",
      "RG"  : "Sachsen",
      "RH"  : "Bayern",
      "RI"  : "Niedersachsen",
      "RID" : "Bayern",
      "RIE" : "Sachsen",
      "RL"  : "Sachsen",
      "RM"  : "Mecklenburg-Vorpommern",
      "RN"  : "Brandenburg",
      "RO"  : "Bayern",
      "ROD" : "Bayern",
      "ROF" : "Hessen",
      "ROK" : "Rheinland-Pfalz",
      "ROL" : "Bayern",
      "ROS" : "Mecklenburg-Vorpommern",
      "ROT" : "Bayern",
      "ROW" : "Niedersachsen",
      "RP"  : "Rheinland-Pfalz",
      "RPL" : "Rheinland-Pfalz",
      "RS"  : "Nordrhein-Westfalen",
      "RSL" : "Sachsen-Anhalt",
      "RT"  : "Baden-Württemberg",
      "RU"  : "Thüringen",
      "RÜD" : "Hessen",
      "RÜG" : "Mecklenburg-Vorpommern",
      "RV"  : "Baden-Württemberg",
      "RW"  : "Baden-Württemberg",
      "RZ"  : "Schleswig-Holstein",
      "S"   : "Baden-Württemberg",
      "SAB" : "Rheinland-Pfalz",
      "SAD" : "Bayern",
      "SÄK" : "Baden-Württemberg",
      "SAL" : "Saarland",
      "SAN" : "Bayern",
      "SAW" : "Sachsen-Anhalt",
      "SB"  : "Saarland",
      "SBG" : "Mecklenburg-Vorpommern",
      "SBK" : "Sachsen-Anhalt",
      "SC"  : "Bayern",
      "SCZ" : "Thüringen",
      "SDH" : "Thüringen",
      "SDL" : "Sachsen-Anhalt",
      "SDT" : "Brandenburg",
      "SE"  : "Schleswig-Holstein",
      "SEB" : "Sachsen",
      "SEE" : "Brandenburg",
      "SEF" : "Bayern",
      "SEL" : "Bayern",
      "SFB" : "Brandenburg",
      "SFT" : "Sachsen-Anhalt",
      "SG"  : "Nordrhein-Westfalen",
      "SGH" : "Sachsen-Anhalt",
      "SH"  : "Schleswig-Holstein",
      "SHA" : "Baden-Württemberg",
      "SHG" : "Niedersachsen",
      "SHK" : "Thüringen",
      "SHL" : "Thüringen",
      "SI"  : "Nordrhein-Westfalen",
      "SIG" : "Baden-Württemberg",
      "SIM" : "Rheinland-Pfalz",
      "SK"  : "Sachsen-Anhalt",
      "SL"  : "Schleswig-Holstein",
      "SLE" : "Nordrhein-Westfalen",
      "SLF" : "Thüringen",
      "SLG" : "Baden-Württemberg",
      "SLK" : "Sachsen-Anhalt",
      "SLN" : "Thüringen",
      "SLS" : "Saarland",
      "SLÜ" : "Hessen",
      "SLZ" : "Thüringen",
      "SM"  : "Thüringen",
      "SMÜ" : "Bayern",
      "SN"  : "Mecklenburg-Vorpommern",
      "SO"  : "Nordrhein-Westfalen",
      "SOB" : "Bayern",
      "SOG" : "Bayern",
      "SOK" : "Thüringen",
      "SÖM" : "Thüringen",
      "SON" : "Thüringen",
      "SP"  : "Rheinland-Pfalz",
      "SPB" : "Brandenburg",
      "SPN" : "Brandenburg",
      "SR"  : "Bayern",
      "SRB" : "Brandenburg",
      "SRO" : "Thüringen",
      "ST"  : "Nordrhein-Westfalen",
      "STA" : "Bayern",
      "STB" : "Mecklenburg-Vorpommern",
      "STD" : "Niedersachsen",
      "STE" : "Bayern",
      "STL" : "Sachsen",
      "STO" : "Baden-Württemberg",
      "SU"  : "Nordrhein-Westfalen",
      "SUL" : "Bayern",
      "SÜW" : "Rheinland-Pfalz",
      "SW"  : "Bayern",
      "SWA" : "Hessen",
      "SY"  : "Niedersachsen",
      "SZ"  : "Niedersachsen",
      "SZB" : "Sachsen",
      "TBB" : "Baden-Württemberg",
      "TDO" : "Sachsen",
      "TE"  : "Nordrhein-Westfalen",
      "TET" : "Mecklenburg-Vorpommern",
      "TF"  : "Brandenburg",
      "TG"  : "Sachsen",
      "THL" : "Thüringen",
      "TIR" : "Bayern",
      "TO"  : "Sachsen",
      "TÖL" : "Bayern",
      "TP"  : "Brandenburg",
      "TR"  : "Rheinland-Pfalz",
      "TS"  : "Bayern",
      "TT"  : "Baden-Württemberg",
      "TÜ"  : "Baden-Württemberg",
      "TUT" : "Baden-Württemberg",
      "ÜB"  : "Baden-Württemberg",
      "UE"  : "Niedersachsen",
      "UEM" : "Mecklenburg-Vorpommern",
      "UER" : "Mecklenburg-Vorpommern",
      "UFF" : "Bayern",
      "UH"  : "Thüringen",
      "UL"  : "Baden-Württemberg",
      "UM"  : "Brandenburg",
      "UN"  : "Nordrhein-Westfalen",
      "USI" : "Hessen",
      "V"   : "Sachsen",
      "VAI" : "Baden-Württemberg",
      "VB"  : "Hessen",
      "VEC" : "Niedersachsen",
      "VER" : "Niedersachsen",
      "VG"  : "Mecklenburg-Vorpommern",
      "VIB" : "Bayern",
      "VIE" : "Nordrhein-Westfalen",
      "VIT" : "Bayern",
      "VK"  : "Saarland",
      "VOH" : "Bayern",
      "VR"  : "Mecklenburg-Vorpommern",
      "VS"  : "Baden-Württemberg",
      "W"   : "Nordrhein-Westfalen",
      "WA"  : "Hessen",
      "WAF" : "Nordrhein-Westfalen",
      "WAK" : "Thüringen",
      "WAN" : "Nordrhein-Westfalen",
      "WAR" : "Nordrhein-Westfalen",
      "WAT" : "Nordrhein-Westfalen",
      "WB"  : "Sachsen-Anhalt",
      "WBG" : "Niedersachsen",
      "WBS" : "Thüringen",
      "WDA" : "Sachsen",
      "WE"  : "Thüringen",
      "WEL" : "Hessen",
      "WEN" : "Bayern",
      "WER" : "Bayern",
      "WES" : "Nordrhein-Westfalen",
      "WF"  : "Niedersachsen",
      "WG"  : "Baden-Württemberg",
      "WHV" : "Niedersachsen",
      "WI"  : "Hessen",
      "WIL" : "Rheinland-Pfalz",
      "WIS" : "Mecklenburg-Vorpommern",
      "WIT" : "Nordrhein-Westfalen",
      "WIZ" : "Hessen",
      "WK"  : "Brandenburg",
      "WL"  : "Niedersachsen",
      "WLG" : "Mecklenburg-Vorpommern",
      "WM"  : "Bayern",
      "WMS" : "Sachsen-Anhalt",
      "WN"  : "Baden-Württemberg",
      "WND" : "Saarland",
      "WO"  : "Rheinland-Pfalz",
      "WOB" : "Niedersachsen",
      "WOH" : "Hessen",
      "WOL" : "Baden-Württemberg",
      "WOR" : "Bayern",
      "WOS" : "Bayern",
      "WR"  : "Sachsen-Anhalt",
      "WRN" : "Mecklenburg-Vorpommern",
      "WS"  : "Bayern",
      "WSF" : "Sachsen-Anhalt",
      "WST" : "Niedersachsen",
      "WSW" : "Sachsen",
      "WT"  : "Baden-Württemberg",
      "WTL" : "Niedersachsen",
      "WTM" : "Niedersachsen",
      "WÜ"  : "Bayern",
      "WUG" : "Bayern",
      "WÜM" : "Bayern",
      "WUN" : "Bayern",
      "WUR" : "Sachsen",
      "WW"  : "Rheinland-Pfalz",
      "WZ"  : "Hessen",
      "WZL" : "Sachsen-Anhalt",
      "Z"   : "Sachsen",
      "ZE"  : "Sachsen-Anhalt",
      "ZEL" : "Rheinland-Pfalz",
      "ZI"  : "Sachsen",
      "ZIG" : "Hessen",
      "ZP"  : "Sachsen",
      "ZR"  : "Thüringen",
      "ZW"  : "Rheinland-Pfalz",
      "ZZ"  : "Sachsen-Anhalt"
    },
    stateClassMapping : {
      "Baden-Württemberg"      : "baden_wuerttemberg",
      "Bayern"                 : "bayern",
      "Berlin"                 : "berlin",
      "Brandenburg"            : "brandenburg",
      "Bremen"                 : "bremen",
      "Hamburg"                : "hamburg",
      "Hessen"                 : "hessen",
      "Mecklenburg-Vorpommern" : "mecklenburg_vorpommern",
      "Niedersachen"           : "niedersachsen",
      "Nordrhein-Westfalen"    : "nordrhein_westfalen",
      "Rheinland-Pfalz"        : "rheinland_pfalz",
      "Saarland"               : "saarland",
      "Sachsen-Anhalt"         : "sachsen_anhalt",
      "Sachsen"                : "sachsen",
      "Schleswig-Holstein"     : "schleswig_holstein",
      "Thüringen"              : "thueringen"
    },
    state : function(county) {
      return $.LicensePlate.codeStateMapping[county];
    },
    stateCode : function(county) {
      return $.LicensePlate.stateClassMapping[$.LicensePlate.state(county)];
    },
    resetCssClasses : function(element) {
      element = $(element);
      if (element.data("classNames")) {
        element.attr("class", element.data("classNames"))
      }
      else {
        element.data("classNames", element.attr("class"));
      }
    },
    onSubmit : function(eve) {
      $(this).find("[name=data]").each(function(){
        var input = $(this);
        var plate = $.LicensePlate.parseData(input); 

        if (plate) {
          var previewElement = input.parents(".line").find(".preview");
          previewElement.html("");

          $.each(plate.county.match(/./g), function() {
            previewElement.append($.LicensePlate.transformCharacter(this));
          });

          $.LicensePlate.resetCssClasses(previewElement);
          previewElement.addClass($.LicensePlate.stateCode(plate.county));

          var separator = $.LicensePlate.generateSeparator();
          separator.attr("title", $.LicensePlate.state(plate.county));
          previewElement.append(separator);

          $.each(plate.letters.match(/./g), function() {
            previewElement.append($.LicensePlate.transformCharacter(this));
          });

          previewElement.append($.LicensePlate.generateWhitespace());

          $.each(plate.numbers.match(/./g), function() {
            previewElement.append($.LicensePlate.transformCharacter(this));
          });

          previewElement.append("<br />");

          previewElement.append($.LicensePlate.generateLink(input.val()));
        }
      });

      
      return false;
    }
  };
})(jQuery);
